# Generated by Django 2.1.1 on 2018-09-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20180920_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
